service: servico-pizzaria
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: 'us-east-1'
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole

functions:
  pedidoRecebidoHandler:
    handler: pedido_recebido.lambda_handler 
    events:
      - eventBridge:
         eventBus:
            - arn:aws:events:${aws:region}:${aws:accountId}:event-bus/pizzaria
         pattern:
           source:
             - com.aws.status
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem  # Permissão específica para inserir itens na tabela
        Resource: "arn:aws:dynamodb:us-east-1:186019336293:table/eventos-pizzaria"

  pizzaProntaHandler:
    handler: pizza_pronta.lambda_handler
    events:
      - eventBridge:
        eventBus:
          - arn:aws:events:${aws:region}:${aws:accountId}:event-bus/pizzaria
        pattern:
          source:
            - com.aws.status
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem  # Permissão específica para inserir itens na tabela
          - sqs:SendMessage  
        Resource:
          - "arn:aws:dynamodb:us-east-1:186019336293:table/eventos-pizzaria"
          - "arn:aws:sqs:us-east-1:186019336293:espera-entrega" 

  consomePizzaPronta:
    handler: consome_pizza_pronta.handler 
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:186019336293:espera-entrega
          batchSize: 1
          enabled: true
